version: '3.4'

services:
  webapp:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=root
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
